[package]
name = "liquid-wrench"
version = "0.1.0"
authors = ["Keith T. Star <keith@pnnl.gov>"]
edition = "2018"

[dependencies]
failure = "0.1.5"
num = "0.2.0"
colored = "1.8.0"

[dependencies.nom]
version = "4.2.3"
features = ["verbose-errors"]
